# Generated by Django 5.2.1 on 2025-05-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dead_line',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
